### ISSUE TITLE
Stat item badges don't display properly in Firefox.

### ISSUE THREAD

**Issue by brycereitano** [BradeyYWhitlock/thecheckpointleague#1]
First off, very cool site to keep up on a community event like this! I don't know how much you want to work on cross-browser compatibility but I noticed that some funkiness on the stat items.

## Expected Behavior
Chrome displays the desired look:
![image](https://user-images.githubusercontent.com/1928691/81455591-e85a5e80-914c-11ea-9bb2-3f7a279b4fa0.png)

## Actual Behavior
Firefox doesn't handle flex and margins the same:
![image](https://user-images.githubusercontent.com/1928691/81455566-d678bb80-914c-11ea-9e33-353b8809a2a3.png)

## Specifications

- OS: Windows 10
- Chrome Version: 81.0.4044.138 (Official Build) (64-bit)
- Firefox Version:  76.0.1 (64-bit)

**Comment by BradeyYWhitlock** [comment]
Thanks for bringing this up! Can't always remember to test every edge case. Got a commit up now that should fix it if you check again!

Link to fix:
https://github.com/BradeyYWhitlock/thecheckpointleague/commit/f3f1c6ef4b29956a58d21e9fc4f428fc496c158e

**Comment by brycereitano** [comment]
Looks good to me! 👍
